# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodlesummer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'XLPagerTabStrip', '~> 8.0'
  # Pods for foodlesummer

  target 'foodlesummerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'foodlesummerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
